import type { CheonbugyeongCharacter } from '../types';

export const CHEONBUGYEONG_CHARS: CheonbugyeongCharacter[] = [
  { char: '一', reading: '일', meaning: '하나, 근원, 시작' },
  { char: '始', reading: '시', meaning: '비로소, 처음' },
  { char: '無', reading: '무', meaning: '없음, 공허' },
  { char: '始', reading: '시', meaning: '시작' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '析', reading: '석', meaning: '나눔, 분석' },
  { char: '三', reading: '삼', meaning: '셋, 하늘/땅/사람' },
  { char: '極', reading: '극', meaning: '극점, 끝' },
  { char: '無', reading: '무', meaning: '없음' },
  { char: '盡', reading: '진', meaning: '다함, 끝' },
  { char: '本', reading: '본', meaning: '근본, 뿌리' },
  { char: '天', reading: '천', meaning: '하늘' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '地', reading: '지', meaning: '땅' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '二', reading: '이', meaning: '둘' },
  { char: '人', reading: '인', meaning: '사람' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '三', reading: '삼', meaning: '셋' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '積', reading: '적', meaning: '쌓음, 축적' },
  { char: '十', reading: '십', meaning: '열, 완성' },
  { char: '鉅', reading: '거', meaning: '크다' },
  { char: '無', reading: '무', meaning: '없음' },
  { char: '匱', reading: '궤', meaning: '상자, 다함' },
  { char: '化', reading: '화', meaning: '변화, 조화' },
  { char: '三', reading: '삼', meaning: '셋' },
  { char: '天', reading: '천', meaning: '하늘' },
  { char: '二', reading: '이', meaning: '둘' },
  { char: '三', reading: '삼', meaning: '셋' },
  { char: '地', reading: '지', meaning: '땅' },
  { char: '二', reading: '이', meaning: '둘' },
  { char: '三', reading: '삼', meaning: '셋' },
  { char: '人', reading: '인', meaning: '사람' },
  { char: '二', reading: '이', meaning: '둘' },
  { char: '三', reading: '삼', meaning: '셋' },
  { char: '大', reading: '대', meaning: '크다' },
  { char: '三', reading: '삼', meaning: '셋' },
  { char: '合', reading: '합', meaning: '합치다' },
  { char: '六', reading: '육', meaning: '여섯' },
  { char: '生', reading: '생', meaning: '낳다, 삶' },
  { char: '七', reading: '칠', meaning: '일곱' },
  { char: '八', reading: '팔', meaning: '여덟' },
  { char: '九', reading: '구', meaning: '아홉' },
  { char: '運', reading: '운', meaning: '운행, 움직임' },
  { char: '三', reading: '삼', meaning: '셋' },
  { char: '四', reading: '사', meaning: '넷' },
  { char: '成', reading: '성', meaning: '이루다' },
  { char: '環', reading: '환', meaning: '고리, 순환' },
  { char: '五', reading: '오', meaning: '다섯' },
  { char: '七', reading: '칠', meaning: '일곱' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '妙', reading: '묘', meaning: '묘하다' },
  { char: '衍', reading: '연', meaning: '퍼지다, 넓히다' },
  { char: '萬', reading: '만', meaning: '일만, 모든' },
  { char: '往', reading: '왕', meaning: '가다' },
  { char: '萬', reading: '만', meaning: '일만, 모든' },
  { char: '來', reading: '래', meaning: '오다' },
  { char: '用', reading: '용', meaning: '쓰다, 작용' },
  { char: '變', reading: '변', meaning: '변하다' },
  { char: '不', reading: '부', meaning: '아니다' },
  { char: '動', reading: '동', meaning: '움직이다' },
  { char: '本', reading: '본', meaning: '근본' },
  { char: '本', reading: '본', meaning: '근본' },
  { char: '心', reading: '심', meaning: '마음' },
  { char: '本', reading: '본', meaning: '근본' },
  { char: '太', reading: '태', meaning: '크다' },
  { char: '陽', reading: '양', meaning: '태양, 밝음' },
  { char: '昻', reading: '앙', meaning: '오르다, 높다' },
  { char: '明', reading: '명', meaning: '밝다' },
  { char: '人', reading: '인', meaning: '사람' },
  { char: '中', reading: '중', meaning: '가운데' },
  { char: '天', reading: '천', meaning: '하늘' },
  { char: '地', reading: '지', meaning: '땅' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '一', reading: '일', meaning: '하나' },
  { char: '終', reading: '종', meaning: '마침, 끝' },
  { char: '無', reading: '무', meaning: '없음' },
  { char: '終', reading: '종', meaning: '마침, 끝' },
  { char: '一', reading: '일', meaning: '하나' },
];
